AWSTemplateFormatVersion: 2010-09-09
Description: Stack for Monetize service
  
# Parameters:
  
#     RestApi: 
#       Type: String
#       Description: The name of your Api.
#       MaxLength: 350
#       MinLength: 1
  
#     RestApiRootResources: 
#       Type: String
#       Description: The name of your Api.
#       MaxLength: 350
#       MinLength: 1
# Metadata:
  
# Mappings:
  
# Conditions:
  
Resources:

  HTTPApiNameSpace: 
    Type: AWS::ServiceDiscovery::HttpNamespace
    Properties: 
      Description: Space for http callable services.
      Name: HTTPServices

  
Outputs:
  HTTPApiNameSpaceArn: 
    Value: !GetAtt HTTPApiNameSpace.Arn
    Description: NameSpace Arn

  HTTPApiNameSpaceId: 
    Value: !GetAtt HTTPApiNameSpace.Id
    Description: NameSpace Id

#   TransactionTopicName: 
#     Value: !GetAtt TransactionDataStore.Outputs.TopicName
#     Description: Domain name S3 bucket

#   TransactionTopicARN: 
#     Value: !GetAtt TransactionDataStore.Outputs.TopicArn
#     Description: Domain name S3 bucket