AWSTemplateFormatVersion: "2010-09-09"
Description: Template for SSL Certificate.
Parameters:
  DomainName:
    Type: String
    Description: Buket Name for website config( eg exemple.com).
    MaxLength: 150
    MinLength: 5
  AlternativeDomainName:
    Type: CommaDelimitedList
    Description: Buket Name for website config( eg exemple.com).
  ValidationMethod:
    Type: String
    Description: Buket Name for website config( eg exemple.com).
    MaxLength: 150
    MinLength: 1
Resources:
  SSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          ValidationDomain: !Ref DomainName
      SubjectAlternativeNames: !Ref AlternativeDomainName
      Tags:
        - Key: Application
          Value: Textras Api
      ValidationMethod: !Ref ValidationMethod
Outputs:
  SSLCertificateArn:
    Value: !Ref SSLCertificate
    Description: SSL Certificate ARN
