AWSTemplateFormatVersion: '2010-09-09'
Description: Push Notification Service.
Parameters:
  KMSKeyArn:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    MaxLength: 350
    MinLength: 5
  KMSKeyID:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    MaxLength: 350
    MinLength: 5
  ArtifactStoreBucketName:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    MaxLength: 50
    MinLength: 5
  GitHubOwner:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    NoEcho: true
  GitHubToken:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    NoEcho: true
  PRODUCT_API:
    Default: generic-project-name
    Description: The name for the project associated with this pipeline (used to namespace resources)
    Type: String
  ORDER_API:
    Default: outPutfile.yaml
    Description: The name for the project associated with this pipeline (used to namespace resources)
    Type: String
  USER_API:
    Default: generic-project-name
    Description: The name for the project associated with this pipeline (used to namespace resources)
    Type: String
  COGNITO_POOL_ID:
    Default: outPutfile.yaml
    Description: The name for the project associated with this pipeline (used to namespace resources)
    Type: String
  COGNITO__CLIENT_POOL_ID:
    Default: outPutfile.yaml
    Description: The name for the project associated with this pipeline (used to namespace resources)
    Type: String
Resources: 

  WebAppBucket: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./team8-webapp.yaml
      Parameters: 
        BucketName: team8.com


  WebAppDeployPipeline: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./codePipeline-github-webapp-service.yaml
      Parameters: 
        KMSKeyArn: !Ref KMSKeyArn
        KMSKeyID: !Ref KMSKeyID
        ArtifactStoreBucketName: !Ref ArtifactStoreBucketName
        PipelineName: hackathon-team8-web-pipeline
        ProjectName: hackathon-team8-web-pipeline
        PipelineDescription: hackathon-team8-web-pipeline
        PipelineBuildSpecFileName: hackathon-team8-web-pipeline-buildSpec.yaml
        PipelineStackName: hackathon-team8-web-pipeline-Stack
        PathRole: /
        PipelineChangeSetName: hackathon-team8-web-pipeline-changeSet
        PipelineOutputFileName: hackathon-team8-web-pipeline-output.yaml
        GitHubRepo: hackathon-team8-web
        GitHubOwner: !Ref GitHubOwner
        GitHubBranch: master
        GitHubToken: !Ref GitHubToken
        WebsiteBucketName: !GetAtt WebAppBucket.Outputs.S3BucketName
        PRODUCT_API: !Ref PRODUCT_API
        ORDER_API: !Ref ORDER_API
        USER_API: !Ref USER_API
        COGNITO_POOL_ID: !Ref COGNITO_POOL_ID
        COGNITO__CLIENT_POOL_ID: !Ref COGNITO__CLIENT_POOL_ID