AWSTemplateFormatVersion: '2010-09-09'
Description: Push Notification Service.
Parameters:
  GitHubToken:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    MaxLength: 350
    MinLength: 5
    NoEcho: true
  GitHubOwner:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    MaxLength: 350
    MinLength: 5
    NoEcho: true
  GitHubBranch:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    MaxLength: 50
    MinLength: 5
  Environnement:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    MaxLength: 50
    MinLength: 3
Resources: 

  ArtifactStore: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./Shared/artifactStore.yaml
      Parameters: 
        KMSDescription: key for ci cd pipeline s3 bucket
        KMSKeyAlias: textras-backend-key
        ArtifactStoreBucketName: textras-backend-pipeline-store

  HostedZone: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./Shared/hostedZone.yaml
      Parameters: 
        Name: !Sub '${Environnement}.textras.com'
        Comment: !Sub 'hosted zone for ${Environnement} Environnement.' 

  SSLCertificate: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./Shared/SSLCertificate.yaml
      Parameters: 
        DomainName: !Sub '${Environnement}.textras.com'
        AlternativeDomainName: !Sub '*.${Environnement}.textras.com' 
        ValidationMethod: DNS

  ServiceDiscovery: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./Shared/serviceDiscovery.yaml

  RestApi: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./Shared/apigateway-rest.yaml
      Parameters: 
        ApiName: Textras-Backend-Api
        ApiKeySourceType: HEADER
        ApiEndpointConfigType: EDGE
        StageName: v1
        HostedZoneId: !GetAtt HostedZone.Outputs.HostedZoneId
        AuthorizerFunctionName: Textras-BackendApiAuthorizer
        AuthorizerFunctionDescription: Authorizer for Textras Backend service RestApi
        AuthorizerFunctionHandler: index.handler
        AuthorizerFunctionMemorySize: "128"
        AuthorizerFunctionRuntimeVersion: nodejs12.x
        AuthorizerFunctionTimeout: "10"

        ServiceTag: Api Service
        ApplicationTag: Backend
        ApiTypeTag: RestApi
        PathRole: /

        CertificateArn: !GetAtt SSLCertificate.Outputs.SSLCertificateArn
        ApiDomainNameParam: !Sub 'cloud.${Environnement}.textras.com'

  TextrasMediaServicePipeline: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./CodePipeline/textras-media-service.yaml
      Parameters: 
        KMSKeyArn: !GetAtt ArtifactStore.Outputs.KMSKeyArn 
        KMSKeyID: !GetAtt ArtifactStore.Outputs.KMSKeyID 
        ArtifactStoreBucketName: !GetAtt ArtifactStore.Outputs.ArtifactStoreBucketName 
        
        ApiLogicalId: !GetAtt RestApi.Outputs.ApiLogicalId 
        ApiRootResource: !GetAtt RestApi.Outputs.ApiRootResource 
        AuthorizerLogicalId: !GetAtt RestApi.Outputs.AuthorizerLogicalId 
        HTTPApiNameSpaceArn: !GetAtt ServiceDiscovery.Outputs.HTTPApiNameSpaceArn
        HTTPApiNameSpaceId: !GetAtt ServiceDiscovery.Outputs.HTTPApiNameSpaceId
        ServiceName: MediaService
        HostedZoneId: !GetAtt HostedZone.Outputs.HostedZoneId
        HostedZoneNameServers: !GetAtt HostedZone.Outputs.HostedZoneNameServers
        CertificateArn: !GetAtt SSLCertificate.Outputs.SSLCertificateArn
        
        PipelineName: textras-media-service
        ProjectName: textras-media-service
        PipelineDescription: textras-media-service
        PipelineBuildSpecFileName: textras-media-service-buildSpec.yaml
        PipelineStackName: textras-media-service-stack
        PathRole: /
        PipelineChangeSetName: textras-media-service-changeSet
        PipelineOutputFileName: textras-media-service-output.yaml
        GitHubRepo: textras-media-service
        GitHubOwner: !Ref GitHubOwner
        GitHubBranch: !Ref GitHubBranch
        GitHubToken: !Ref GitHubToken

        
  TextrasMonetizeServicePipeline: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./CodePipeline/textras-monetize-service.yaml
      Parameters: 
        KMSKeyArn: !GetAtt ArtifactStore.Outputs.KMSKeyArn 
        KMSKeyID: !GetAtt ArtifactStore.Outputs.KMSKeyID 
        ArtifactStoreBucketName: !GetAtt ArtifactStore.Outputs.ArtifactStoreBucketName 
        
        ApiLogicalId: !GetAtt RestApi.Outputs.ApiLogicalId 
        ApiRootResource: !GetAtt RestApi.Outputs.ApiRootResource 
        AuthorizerLogicalId: !GetAtt RestApi.Outputs.AuthorizerLogicalId 
        HTTPApiNameSpaceArn: !GetAtt ServiceDiscovery.Outputs.HTTPApiNameSpaceArn
        HTTPApiNameSpaceId: !GetAtt ServiceDiscovery.Outputs.HTTPApiNameSpaceId
        ServiceName: MonetizeService
        HostedZoneId: !GetAtt HostedZone.Outputs.HostedZoneId
        HostedZoneNameServers: !GetAtt HostedZone.Outputs.HostedZoneNameServers
        CertificateArn: !GetAtt SSLCertificate.Outputs.SSLCertificateArn
        
        PipelineName: textras-monetize-service
        ProjectName: textras-monetize-service
        PipelineDescription: textras-monetize-service
        PipelineBuildSpecFileName: textras-monetize-service-buildSpec.yaml
        PipelineStackName: textras-monetize-service-stack
        PathRole: /
        PipelineChangeSetName: textras-monetize-service-changeSet
        PipelineOutputFileName: textras-monetize-service-output.yaml
        GitHubRepo: textras-monetize-service
        GitHubOwner: !Ref GitHubOwner
        GitHubBranch: !Ref GitHubBranch
        GitHubToken: !Ref GitHubToken

        
  TextrasPaymentServicePipeline: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./CodePipeline/textras-payment-service.yaml
      Parameters: 
        KMSKeyArn: !GetAtt ArtifactStore.Outputs.KMSKeyArn 
        KMSKeyID: !GetAtt ArtifactStore.Outputs.KMSKeyID 
        ArtifactStoreBucketName: !GetAtt ArtifactStore.Outputs.ArtifactStoreBucketName 
        
        ApiLogicalId: !GetAtt RestApi.Outputs.ApiLogicalId 
        ApiRootResource: !GetAtt RestApi.Outputs.ApiRootResource 
        AuthorizerLogicalId: !GetAtt RestApi.Outputs.AuthorizerLogicalId 
        HTTPApiNameSpaceArn: !GetAtt ServiceDiscovery.Outputs.HTTPApiNameSpaceArn
        HTTPApiNameSpaceId: !GetAtt ServiceDiscovery.Outputs.HTTPApiNameSpaceId
        ServiceName: PaymentService
        HostedZoneId: !GetAtt HostedZone.Outputs.HostedZoneId
        HostedZoneNameServers: !GetAtt HostedZone.Outputs.HostedZoneNameServers
        CertificateArn: !GetAtt SSLCertificate.Outputs.SSLCertificateArn
        
        PipelineName: textras-payment-service
        ProjectName: textras-payment-service
        PipelineDescription: textras-payment-service
        PipelineBuildSpecFileName: textras-payment-service-buildSpec.yaml
        PipelineStackName: textras-payment-service-stack
        PathRole: /
        PipelineChangeSetName: textras-payment-service-changeSet
        PipelineOutputFileName: textras-payment-service-output.yaml
        GitHubRepo: textras-payment-service
        GitHubOwner: !Ref GitHubOwner
        GitHubBranch: !Ref GitHubBranch
        GitHubToken: !Ref GitHubToken

        
  TextrasUserManagementServicePipeline: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./CodePipeline/textras-userManagement-service.yaml
      Parameters: 
        KMSKeyArn: !GetAtt ArtifactStore.Outputs.KMSKeyArn 
        KMSKeyID: !GetAtt ArtifactStore.Outputs.KMSKeyID 
        ArtifactStoreBucketName: !GetAtt ArtifactStore.Outputs.ArtifactStoreBucketName 
        
        ApiLogicalId: !GetAtt RestApi.Outputs.ApiLogicalId 
        ApiRootResource: !GetAtt RestApi.Outputs.ApiRootResource 
        AuthorizerLogicalId: !GetAtt RestApi.Outputs.AuthorizerLogicalId 
        HTTPApiNameSpaceArn: !GetAtt ServiceDiscovery.Outputs.HTTPApiNameSpaceArn
        HTTPApiNameSpaceId: !GetAtt ServiceDiscovery.Outputs.HTTPApiNameSpaceId
        ServiceName: UserManagementService
        HostedZoneId: !GetAtt HostedZone.Outputs.HostedZoneId
        HostedZoneNameServers: !GetAtt HostedZone.Outputs.HostedZoneNameServers
        CertificateArn: !GetAtt SSLCertificate.Outputs.SSLCertificateArn
        
        PipelineName: textras-userManagement-service
        ProjectName: textras-userManagement-service
        PipelineDescription: textras-userManagement-service
        PipelineBuildSpecFileName: textras-userManagement-service-buildSpec.yaml
        PipelineStackName: textras-userManagement-service-stack
        PathRole: /
        PipelineChangeSetName: textras-userManagement-service-changeSet
        PipelineOutputFileName: textras-userManagement-service-output.yaml
        GitHubRepo: textras-userManagement-service
        GitHubOwner: !Ref GitHubOwner
        GitHubBranch: !Ref GitHubBranch
        GitHubToken: !Ref GitHubToken

        
