AWSTemplateFormatVersion: '2010-09-09'
Description: Push Notification Service.
Parameters:
  KMSKeyArn:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    MaxLength: 350
    MinLength: 5
  KMSKeyID:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    MaxLength: 350
    MinLength: 5
  ArtifactStoreBucketName:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    MaxLength: 50
    MinLength: 5
  GitHubOwner:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    NoEcho: true
  GitHubToken:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    NoEcho: true
Resources: 

  AuthenticationService: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./Authentication/index.yaml

  WebClientPipeline: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./WebClientPipeline/index.yaml
      Parameters: 
        KMSKeyArn: !Ref KMSKeyArn
        KMSKeyID: !Ref KMSKeyID
        ArtifactStoreBucketName: !Ref ArtifactStoreBucketName
        GitHubToken: !Ref GitHubToken
        GitHubOwner: !Ref GitHubOwner
        PRODUCT_API: test
        ORDER_API: test
        USER_API: test
        COGNITO_POOL_ID: !GetAtt AuthenticationService.Outputs.UserPoolLogicalId
        COGNITO__CLIENT_POOL_ID: !GetAtt AuthenticationService.Outputs.UserPoolLogicalClientId


Outputs:
  AuthenticationTopicArn:
    Value: !GetAtt AuthenticationService.Outputs.AuthenticationTopicArn
    Export:
      Name: !Sub ${AWS::StackName}-AuthenticationTopicArn
  UserPoolLogicalId:
    Value: !GetAtt AuthenticationService.Outputs.UserPoolLogicalId
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolLogicalId
  UserPoolLogicalClientId:
    Value: !GetAtt AuthenticationService.Outputs.UserPoolLogicalClientId
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolLogicalClientId
  UserPoolProviderName:
    Value: !GetAtt AuthenticationService.Outputs.UserPoolProviderName
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolProviderName
  UserPoolProviderURL:
    Value: !GetAtt AuthenticationService.Outputs.UserPoolProviderURL
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolProviderURL
  UserPoolArn:
    Value: !GetAtt AuthenticationService.Outputs.UserPoolArn 
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolArn