AWSTemplateFormatVersion: '2010-09-09'
Description: Push Notification Service.
Parameters:
  KMSKeyArn:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    MaxLength: 350
    MinLength: 5
  KMSKeyID:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    MaxLength: 350
    MinLength: 5
  ArtifactStoreBucketName:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    MaxLength: 50
    MinLength: 5
  GitHubOwner:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    NoEcho: true
  GitHubToken:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    NoEcho: true
Resources: 

  AuthenticationService: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./Authentication/index.yaml

  RestApi: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./Shared/apigateway-rest.yaml
      Parameters: 
        ApiName: Team8-Backend-Api
        ApiKeySourceType: HEADER
        ApiEndpointConfigType: EDGE
        StageName: v1
        # HostedZoneId: !GetAtt HostedZone.Outputs.HostedZoneId
        AuthorizerFunctionName: team8-BackendApiAuthorizer
        AuthorizerFunctionDescription: Authorizer for team8 Backend service RestApi
        AuthorizerFunctionHandler: index.handler
        AuthorizerFunctionMemorySize: "128"
        AuthorizerFunctionRuntimeVersion: nodejs12.x
        AuthorizerFunctionTimeout: "10"
        CognitoPoolID: !GetAtt AuthenticationService.Outputs.UserPoolLogicalId
        CognitoClientID: !GetAtt AuthenticationService.Outputs.UserPoolLogicalClientId
        ServiceTag: Api Service
        ApplicationTag: Backend
        ApiTypeTag: RestApi
        PathRole: /

        # CertificateArn: !GetAtt SSLCertificate.Outputs.SSLCertificateArn
        # ApiDomainNameParam: !Sub 'cloud.${Environnement}.textras.com'

  WebClientPipeline: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./WebClientPipeline/index.yaml
      Parameters: 
        KMSKeyArn: !Ref KMSKeyArn
        KMSKeyID: !Ref KMSKeyID
        ArtifactStoreBucketName: !Ref ArtifactStoreBucketName
        GitHubToken: !Ref GitHubToken
        GitHubOwner: !Ref GitHubOwner
        BackendAPI: test
        # BackendAPI: !Sub
        #   - https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${RestApiStage}
        #   - RestApi: !GetAtt RestApi.Outputs.ApiLogicalId 
        #     RestApiStage: !GetAtt RestApi.Outputs.StageLogicalId
        ProductAPI: test
        OrderAPI: test
        UserAPI: test
        CognitoPoolID: !GetAtt AuthenticationService.Outputs.UserPoolLogicalId
        CognitoClientID: !GetAtt AuthenticationService.Outputs.UserPoolLogicalClientId

  ActivityServicePipeline: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./CodePipeline/codePipeline-github-activity-service.yaml
      Parameters: 
        KMSKeyArn: !Ref KMSKeyArn
        KMSKeyID: !Ref KMSKeyID
        ArtifactStoreBucketName:  !Ref ArtifactStoreBucketName
        PipelineName: team8-activity-service
        ProjectName: team8-activity-service
        PipelineDescription: team8-activity-service
        PipelineBuildSpecFileName: team8-activity-service-buildSpec.yaml
        PipelineStackName: team8-activity-service-Stack
        PathRole: /
        PipelineChangeSetName: team8-activity-service-changeSet
        PipelineOutputFileName: team8-activity-service-output.yaml
        GitHubRepo: hackathon-team8-activity-service
        GitHubOwner: !Ref GitHubOwner
        GitHubBranch: master
        GitHubToken: !Ref GitHubToken
        AuthenticationTopicArn: !GetAtt AuthenticationService.Outputs.AuthenticationTopicArn 
        ApiLogicalId: !GetAtt RestApi.Outputs.ApiLogicalId 
        ApiRootResource: !GetAtt RestApi.Outputs.ApiRootResource 
        UserResource: !GetAtt RestApi.Outputs.UserResource 
        AuthorizerLogicalId: !GetAtt RestApi.Outputs.AuthorizerLogicalId 
        CognitoPoolID: !GetAtt AuthenticationService.Outputs.UserPoolLogicalId
        CognitoClientID: !GetAtt AuthenticationService.Outputs.UserPoolLogicalClientId
        
  OrganizationServicePipeline: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./CodePipeline/codePipeline-github-organization-service.yaml
      Parameters: 
        KMSKeyArn: !Ref KMSKeyArn
        KMSKeyID: !Ref KMSKeyID
        ArtifactStoreBucketName:  !Ref ArtifactStoreBucketName
        PipelineName: team8-organization-service
        ProjectName: team8-organization-service
        PipelineDescription: team8-organization-service
        PipelineBuildSpecFileName: team8-organization-service-buildSpec.yaml
        PipelineStackName: team8-organization-service-Stack
        PathRole: /
        PipelineChangeSetName: team8-organization-service-changeSet
        PipelineOutputFileName: team8-organization-service-output.yaml
        GitHubRepo: hackathon-team8-organization-service
        GitHubOwner: !Ref GitHubOwner
        GitHubBranch: master
        GitHubToken: !Ref GitHubToken
        AuthenticationTopicArn: !GetAtt AuthenticationService.Outputs.AuthenticationTopicArn 
        ApiLogicalId: !GetAtt RestApi.Outputs.ApiLogicalId 
        ApiRootResource: !GetAtt RestApi.Outputs.ApiRootResource 
        UserResource: !GetAtt RestApi.Outputs.UserResource 
        AuthorizerLogicalId: !GetAtt RestApi.Outputs.AuthorizerLogicalId 
        CognitoPoolID: !GetAtt AuthenticationService.Outputs.UserPoolLogicalId
        CognitoClientID: !GetAtt AuthenticationService.Outputs.UserPoolLogicalClientId
        
  TeamServicePipeline: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./CodePipeline/codePipeline-github-team-service.yaml
      Parameters: 
        KMSKeyArn: !Ref KMSKeyArn
        KMSKeyID: !Ref KMSKeyID
        ArtifactStoreBucketName:  !Ref ArtifactStoreBucketName
        PipelineName: team8-team-service
        ProjectName: team8-team-service
        PipelineDescription: team8-team-service
        PipelineBuildSpecFileName: team8-team-service-buildSpec.yaml
        PipelineStackName: team8-team-service-Stack
        PathRole: /
        PipelineChangeSetName: team8-team-service-changeSet
        PipelineOutputFileName: team8-team-service-output.yaml
        GitHubRepo: hackathon-team8-team-service
        GitHubOwner: !Ref GitHubOwner
        GitHubBranch: master
        GitHubToken: !Ref GitHubToken
        ApiLogicalId: !GetAtt RestApi.Outputs.ApiLogicalId
        AuthenticationTopicArn: !GetAtt AuthenticationService.Outputs.AuthenticationTopicArn  
        ApiRootResource: !GetAtt RestApi.Outputs.ApiRootResource 
        UserResource: !GetAtt RestApi.Outputs.UserResource 
        AuthorizerLogicalId: !GetAtt RestApi.Outputs.AuthorizerLogicalId 
        CognitoPoolID: !GetAtt AuthenticationService.Outputs.UserPoolLogicalId
        CognitoClientID: !GetAtt AuthenticationService.Outputs.UserPoolLogicalClientId
        
  BotServicePipeline: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./CodePipeline/codePipeline-github-bot-service.yaml
      Parameters: 
        KMSKeyArn: arn:aws:kms:us-east-1:998237141726:key/bb002d6c-941a-439f-81d8-95facc1dd12a
        KMSKeyID: bb002d6c-941a-439f-81d8-95facc1dd12a
        ArtifactStoreBucketName: team8-bot-service-artifact-store
        KMSKeyArnRegional: !Ref KMSKeyArn
        KMSKeyIDRegional: !Ref KMSKeyID
        ArtifactStoreBucketNameRegional: !Ref ArtifactStoreBucketName
        PipelineName: team8-bot-service
        ProjectName: team8-bot-service
        PipelineDescription: team8-bot-service
        PipelineBuildSpecFileName: team8-bot-service-buildSpec.yaml
        PipelineStackName: team8-bot-service-Stack
        PathRole: /
        PipelineChangeSetName: team8-bot-service-changeSet
        PipelineOutputFileName: team8-bot-service-output.yaml
        GitHubRepo: hackathon-team8-bot-service
        GitHubOwner: !Ref GitHubOwner
        GitHubBranch: master
        GitHubToken: !Ref GitHubToken
        ApiLogicalId: !GetAtt RestApi.Outputs.ApiLogicalId 
        ApiRootResource: !GetAtt RestApi.Outputs.ApiRootResource 
        UserResource: !GetAtt RestApi.Outputs.UserResource 
        AuthorizerLogicalId: !GetAtt RestApi.Outputs.AuthorizerLogicalId 

Outputs:
  AuthenticationTopicArn:
    Value: !GetAtt AuthenticationService.Outputs.AuthenticationTopicArn
    Export:
      Name: !Sub ${AWS::StackName}-AuthenticationTopicArn
  UserPoolLogicalId:
    Value: !GetAtt AuthenticationService.Outputs.UserPoolLogicalId
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolLogicalId
  UserPoolLogicalClientId:
    Value: !GetAtt AuthenticationService.Outputs.UserPoolLogicalClientId
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolLogicalClientId
  UserPoolProviderName:
    Value: !GetAtt AuthenticationService.Outputs.UserPoolProviderName
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolProviderName
  UserPoolProviderURL:
    Value: !GetAtt AuthenticationService.Outputs.UserPoolProviderURL
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolProviderURL
  UserPoolArn:
    Value: !GetAtt AuthenticationService.Outputs.UserPoolArn 
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolArn