AWSTemplateFormatVersion: "2010-09-09"
Description: 'S3 Bucket config for code base'
Parameters:
  KMSDescription:
    Type: String
    Description: Add a description for the KMS key.
    MaxLength: 350
    MinLength: 5
  KMSKeyAlias:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    MaxLength: 50
    MinLength: 5
  ArtifactStoreBucketName:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    MaxLength: 50
    MinLength: 5
Resources:
  KMSKey: 
    Type: AWS::KMS::Key
    Properties: 
      Description: !Ref KMSDescription
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Id: !Ref AWS::StackName
        Statement:
          -
            Sid: Allows admin of the key
            Effect: Allow
            Principal:
              AWS: 
                - !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - "kms:Create*"
              - "kms:Describe*"
              - "kms:Enable*"
              - "kms:List*"
              - "kms:Put*"
              - "kms:Update*"
              - "kms:Revoke*"
              - "kms:Disable*"
              - "kms:Get*"
              - "kms:Delete*"
              - "kms:ScheduleKeyDeletion"
              - "kms:CancelKeyDeletion"
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"
          -
            Sid: Allow use of the key for CryptoGraphy Lambda
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"
            Condition: 
              ForAnyValue:StringLike: 
                aws:PrincipalOrgPaths: 
                  - "o-icf34dwnsl/r-5oqx/ou-5oqx-fnb16u8x/*"
          - Sid: Allow use of the key for CryptoGraphy Lambda
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - kms:CreateGrant
              - kms:ListGrants
              - kms:RevokeGrant
            Resource: "*"
            Condition:
              Bool: 
                kms:GrantIsForAWSResource: true
  KMSAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${KMSKeyAlias}
      TargetKeyId: !Ref KMSKey

  ArtifactStoreBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref ArtifactStoreBucketName
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault: 
              KMSMasterKeyID: !Ref KMSKey
              SSEAlgorithm: aws:kms
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Application
          Value: Code Build

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref ArtifactStoreBucket
      PolicyDocument: 
        Version: '2012-10-17'
        Id: SSEAndSSLPolicy
        Statement:
        - Sid: DenyUnEncryptedObjectUploads
          Effect: Deny
          Principal: "*"
          Action: s3:PutObject
          Resource: !Sub arn:aws:s3:::${ArtifactStoreBucket}/*
          Condition:
            StringNotEquals:
              s3:x-amz-server-side-encryption: "aws:kms"
        - Sid: DenyInsecureConnections
          Effect: Deny
          Principal: "*"
          Action: s3:*
          Resource: !Sub arn:aws:s3:::${ArtifactStoreBucket}/*
          Condition:
            Bool:
              aws:SecureTransport: 'false'
        - Action:
            - s3:*
          Effect: Allow
          Resource:
            - !Sub arn:aws:s3:::${ArtifactStoreBucket}
            - !Sub arn:aws:s3:::${ArtifactStoreBucket}/*
          Condition: 
            ForAnyValue:StringLike: 
              aws:PrincipalOrgPaths: 
                - "o-icf34dwnsl/r-5oqx/ou-5oqx-fnb16u8x/*"
          Principal:
            AWS: '*'
              # - !Sub arn:aws:iam::${AWS::AccountId}:root
              # - !Sub arn:aws:iam::${AWS::AccountId}:role/${PipelineName}-codebuild-role
              # - !Sub arn:aws:iam::${AWS::AccountId}:role/${PipelineName}-role
              # - !Sub 
              #   - arn:aws:iam::${AccountId}:root
              #   - AccountId: !FindInMap [ Setting, Account, Staging ]


Outputs:
  KMSKeyArn:
    Value: !GetAtt KMSKey.Arn
  KMSKeyID:
    Value: !Ref KMSKey
  ArtifactStoreBucketName:
    Value: !Ref ArtifactStoreBucket



